################################  服务器配置  ################################
server:
  servlet:
    context-path: /dreamccmall
  port: 9099
################################ 数据源配置  ################################
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
    prefix: classpath:/webapp/
    suffix: .html
  messages:
    basename: i18n.login

################################ mybatis配置  ################################
mybatis:
  config-location: classpath:commons/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml

################################ redis配置  ################################
redis:
  max:
    total: 20
    idle: 20
  min:
    idle: 20
  test:
    borrow: true
    return: true